name: Get Changed Folders

on:
  push:
    branches:
      - main  # Change to your target branch

jobs:
  - uses: Stockopedia/action-get-changed-files@v1
    id: changed
    with:
      foldersOnly: true
      format: json
  - name: Echo
    run: echo ${{ steps.get_changed.outputs.changed }}

