name: Get Changed Folders

on:
  push:
    branches:
      - main  # Change to your target branch

jobs:
  get-changed-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Get changed folders
      id: changed_folders
      run: |
        changed_folders=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs -I {} dirname {})
        echo "Changed folders: $changed_folders"
        echo "::set-output name=changed_folders::$changed_folders"

    - name: Use the changed folders in the next step
      run: echo "The changed folders are ${{ steps.changed_folders.outputs.changed_folders }}"
